"""Update Product model with all new fields

Revision ID: b27d32a57fcd
Revises: e14c90805e1d
Create Date: 2025-06-18 10:39:52.076936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27d32a57fcd'
down_revision = 'e14c90805e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sizes', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('colors', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_gallery', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('publish_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('publish_date')
        batch_op.drop_column('visibility')
        batch_op.drop_column('image_gallery')
        batch_op.drop_column('tags')
        batch_op.drop_column('colors')
        batch_op.drop_column('sizes')
        batch_op.drop_column('discount')
        batch_op.drop_column('sale_price')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
