"""Change image_url to image_data

Revision ID: ce6c9cfdf914
Revises: 8252665c83fe
Create Date: 2025-06-28 11:26:37.588676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce6c9cfdf914'
down_revision = '8252665c83fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(length=16777215), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(length=16777215), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_data')

    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
