"""Initial migration

Revision ID: e2a77861ee7d
Revises: 
Create Date: 2025-08-08 13:30:41.607585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a77861ee7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_user_role_id_roles',  # explicit name for FK constraint
            'roles',
            ['role_id'],
            ['id']
        )
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_user_role_id_roles', type_='foreignkey')  # drop by name
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
