---
name: Full CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: infinitydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build all Docker images
        run: docker compose build --pull

      - name: Start Docker containers
        run: |
          docker compose up -d
          echo "Waiting 20s for containers to start..."
          sleep 20
          docker ps

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API on port 5000..."
          for i in {1..30}; do
            if curl -s http://localhost:5000/health; then
              echo "API is up!"
              break
            fi
            echo "Waiting 2 seconds..."
            sleep 2
          done

      - name: Run unit tests
        run: |
          pytest tests/ \
            --maxfail=1 \
            --disable-warnings \
            -v
        env:
          PYTHONPATH: ${{ github.workspace }}

  push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push API image
        run: |
          docker compose build api
          docker tag infinitystyleverse-main-api \
            ${{ secrets.DOCKER_USERNAME }}/infinitystyleverse-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/infinitystyleverse-api:latest

      - name: Build and Push Worker image
        run: |
          docker compose build worker
          docker tag infinitystyleverse-main-worker \
            ${{ secrets.DOCKER_USERNAME }}/infinitystyleverse-worker:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/infinitystyleverse-worker:latest

      - name: Build and Push Flower image
        run: |
          docker compose build flower
          docker tag infinitystyleverse-main-flower \
            ${{ secrets.DOCKER_USERNAME }}/infinitystyleverse-flower:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/infinitystyleverse-flower:latest
